#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=4.1.0
PACKAGE=chalk-cli
TOOL=chalk
DIRECTORY=$(dirname $0)

PERSISTENT_FILE_STORAGE=/ocean
if [ ! -d $PERSISTENT_FILE_STORAGE ]; then
	singularity exec $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
else
	singularity exec -B $PERSISTENT_FILE_STORAGE $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
fi
