Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 4.1.0

%post
    apk add --update nodejs npm

####################################################################################
%appinstall chalk-cli
    npm install --global chalk-cli

%apphelp chalk-cli
    chalk-cli --help

%apprun chalk-cli
    chalk-cli "$@"
